### ISSUE TITLE
Keyframes get incorrectly scoped

### ISSUE THREAD

**Issue by maxemilian-jco** [jackall3n/postcss-scope#21]
Hey, I have an issue with this plugin, specifically when using animations/keyframes, and also Tailwinds animations.

With the following code (copied from Tailwind to reproduce issue):
```css
@keyframes spin {
	to {
		transform: rotate(360deg);
	}
}
.animate-spin {
	animation: spin 1s linear infinite;
}
```

The output becomes (example scope: '.test'):
```css
@keyframes spin {
	.test to {
		transform: rotate(360deg);
	}
}
.test .animate-spin {
	animation: spin 1s linear infinite;
}
```

If you notice the `.test` before the `to` in the keyframe, this unfortunately breaks the animation.

I can get around this by copying the CSS to a new file and ignoring that file. However, it is not an elegant solution when dealing with external CSS libraries such as Tailwind.
